// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hzzzoylajeitnvjglyku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6enpveWxhamVpdG52amdseWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMzE5NDAsImV4cCI6MjA4NzYwNzk0MH0.SIey91amMzcY37E3hzPRfvlsvx5kl3djfvnKQSJI_Qw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);